services:
  - type: web
    name: vscode-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: workspace
      mountPath: /workspace
      sizeGB: 1 